-- FILE: 01_SETUP.SQL

USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE WAREHOUSE SUPPLY_CHAIN_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

CREATE OR REPLACE DATABASE SUPPLY_CHAIN_DB;
CREATE OR REPLACE SCHEMA SUPPLY_CHAIN_DB.RAW;
CREATE OR REPLACE SCHEMA SUPPLY_CHAIN_DB.CLEAN;
CREATE OR REPLACE SCHEMA SUPPLY_CHAIN_DB.ANALYTICS;
USE WAREHOUSE SUPPLY_CHAIN_WH;
USE DATABASE SUPPLY_CHAIN_DB;
