USE SCHEMA SUPPLY_CHAIN_DB.RAW;

CREATE OR REPLACE FILE FORMAT SUPPLY_CHAIN_DB.RAW.CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = ('NULL', 'null', '')
EMPTY_FIELD_AS_NULL = TRUE
TRIM_SPACE = TRUE
ENCODING = 'UTF8'
REPLACE_INVALID_CHARACTERS = TRUE;