USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE STORAGE INTEGRATION S3_INT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::066113723620:role/snowflake_supplychain'     -- COPY AND PASTE ARN FROM IAM IN AWS
STORAGE_ALLOWED_LOCATIONS = ('s3://snowflake-supply-chain-rp/');                  -- COPY AND PASTE THE STORAGE DIRECTORY


DESC STORAGE INTEGRATION S3_INT;        -- COPY STORAGE_AWS_IAM_USER_ARN , STORAGE_AWS_EXTERNAL_ID AND GO TO AWS IAM (SEE STEPS BELOW)


--Create External Stage
CREATE OR REPLACE STAGE SUPPLY_CHAIN_DB.RAW.SUPPLY_CHAIN_S3_STAGE
URL = 's3://snowflake-supply-chain-rp/'
STORAGE_INTEGRATION = S3_INT
FILE_FORMAT = CSV_FORMAT;


LIST @SUPPLY_CHAIN_DB.RAW.SUPPLY_CHAIN_S3_STAGE;   -- VERIFY FILES

SHOW STAGES IN SCHEMA SUPPLY_CHAIN_DB.RAW;   -- SHOW ALL THE STAGES