CREATE OR REPLACE TABLE SUPPLY_CHAIN_DB.RAW.RAW_DATACO_SUPPLY_CHAIN (
    type VARCHAR,
    days_for_shipping_real VARCHAR,
    days_for_shipment_scheduled VARCHAR,
    benefit_per_order VARCHAR,
    sales_per_customer VARCHAR,
    delivery_status VARCHAR,
    late_delivery_risk VARCHAR,
    category_id VARCHAR,
    category_name VARCHAR,
    customer_city VARCHAR,
    customer_country VARCHAR,
    customer_email VARCHAR,
    customer_fname VARCHAR,
    customer_id VARCHAR,
    customer_lname VARCHAR,
    customer_password VARCHAR,
    customer_segment VARCHAR,
    customer_state VARCHAR,
    customer_street VARCHAR,
    customer_zipcode VARCHAR,
    department_id VARCHAR,
    department_name VARCHAR,
    latitude VARCHAR,
    longitude VARCHAR,
    market VARCHAR,
    order_city VARCHAR,
    order_country VARCHAR,
    order_customer_id VARCHAR,
    order_date VARCHAR,
    order_id VARCHAR,
    order_item_cardprod_id VARCHAR,
    order_item_discount VARCHAR,
    order_item_discount_rate VARCHAR,
    order_item_id VARCHAR,
    order_item_product_price VARCHAR,
    order_item_profit_ratio VARCHAR,
    order_item_quantity VARCHAR,
    sales VARCHAR,
    order_item_total VARCHAR,
    order_profit_per_order VARCHAR,
    order_region VARCHAR,
    order_state VARCHAR,
    order_status VARCHAR,
    order_zipcode VARCHAR,
    product_card_id VARCHAR,
    product_category_id VARCHAR,
    product_description VARCHAR,
    product_image VARCHAR,
    product_name VARCHAR,
    product_price VARCHAR,
    product_status VARCHAR,
    shipping_date VARCHAR,
    shipping_mode VARCHAR

);

SELECT * FROM SUPPLY_CHAIN_DB.RAW.RAW_DATACO_SUPPLY_CHAIN;
