COPY INTO SUPPLY_CHAIN_DB.RAW.RAW_DATACO_SUPPLY_CHAIN
FROM @SUPPLY_CHAIN_DB.RAW.SUPPLY_CHAIN_S3_STAGE
FILES = ('DataCoSupplyChainDataset.csv')
FILE_FORMAT = SUPPLY_CHAIN_DB.RAW.CSV_FORMAT
ON_ERROR = 'CONTINUE';

SELECT * FROM SUPPLY_CHAIN_DB.RAW.RAW_DATACO_SUPPLY_CHAIN;
