USE DATABASE SUPPLY_CHAIN_DB;

USE SCHEMA CLEAN;

CREATE OR REPLACE TABLE SUPPLY_CHAIN_DB.CLEAN.CLEAN_SUPPLY_CHAIN AS
SELECT 
    TYPE,
    TRY_TO_NUMBER(DAYS_FOR_SHIPPING_REAL) AS DAYS_FOR_SHIPPING_REAL,
    TRY_TO_NUMBER(DAYS_FOR_SHIPMENT_SCHEDULED) AS DAYS_FOR_SHIPMENT_SCHEDULED,
    TRY_TO_DECIMAL(BENEFIT_PER_ORDER, 10, 2) AS BENEFIT_PER_ORDER,
    TRY_TO_DECIMAL(SALES_PER_CUSTOMER, 10, 2) AS SALES_PER_CUSTOMER,
    DELIVERY_STATUS,
    TRY_TO_NUMBER(LATE_DELIVERY_RISK) AS LATE_DELIVERY_RISK,
    TRY_TO_NUMBER(CATEGORY_ID) AS CATEGORY_ID,
    CATEGORY_NAME,
    CUSTOMER_CITY,
    CUSTOMER_COUNTRY,
    CUSTOMER_SEGMENT,
    CUSTOMER_STATE,
    TRY_TO_NUMBER(DEPARTMENT_ID) AS DEPARTMENT_ID,
    DEPARTMENT_NAME,
    MARKET,
    ORDER_CITY,
    ORDER_COUNTRY,
    TRY_TO_NUMBER(ORDER_CUSTOMER_ID) AS ORDER_CUSTOMER_ID,
    TRY_TO_TIMESTAMP(ORDER_DATE,'MM/DD/YYYY HH24:MI') AS ORDER_DATE,
    TRY_TO_NUMBER(ORDER_ID) AS ORDER_ID,
    TRY_TO_DECIMAL(ORDER_ITEM_DISCOUNT, 10, 2) AS ORDER_ITEM_DISCOUNT,
    TRY_TO_DECIMAL(ORDER_ITEM_DISCOUNT_RATE, 10, 4) AS ORDER_ITEM_DISCOUNT_RATE,
    TRY_TO_NUMBER(ORDER_ITEM_ID) AS ORDER_ITEM_ID,
    TRY_TO_DECIMAL(ORDER_ITEM_PRODUCT_PRICE, 10, 2) AS ORDER_ITEM_PRODUCT_PRICE,
    TRY_TO_DECIMAL(ORDER_ITEM_PROFIT_RATIO, 10, 4) AS ORDER_ITEM_PROFIT_RATIO,
    TRY_TO_NUMBER(ORDER_ITEM_QUANTITY) AS ORDER_ITEM_QUANTITY,
    TRY_TO_DECIMAL(SALES, 10, 2) AS SALES,
    TRY_TO_DECIMAL(ORDER_ITEM_TOTAL, 10, 2) AS ORDER_ITEM_TOTAL,
    TRY_TO_DECIMAL(ORDER_PROFIT_PER_ORDER, 10, 2) AS ORDER_PROFIT_PER_ORDER,
    ORDER_REGION,
    ORDER_STATE,
    ORDER_STATUS,
    PRODUCT_NAME,
    TRY_TO_DECIMAL(PRODUCT_PRICE, 10, 2) AS PRODUCT_PRICE,
    TRY_TO_NUMBER(PRODUCT_STATUS) AS PRODUCT_STATUS,
    TRY_TO_TIMESTAMP(SHIPPING_DATE,'MM/DD/YYYY HH24:MI') AS SHIPPING_DATE,
    SHIPPING_MODE
FROM SUPPLY_CHAIN_DB.RAW.RAW_DATACO_SUPPLY_CHAIN;


SELECT * FROM SUPPLY_CHAIN_DB.CLEAN.CLEAN_SUPPLY_CHAIN;



-- DATA VALIDATION

SELECT * FROM SUPPLY_CHAIN_DB.RAW.RAW_DATACO_SUPPLY_CHAIN;
SELECT * FROM SUPPLY_CHAIN_DB.CLEAN.CLEAN_SUPPLY_CHAIN;


--DATA TYPE CHECK

DESC TABLE SUPPLY_CHAIN_DB.RAW.RAW_DATACO_SUPPLY_CHAIN;
DESC TABLE SUPPLY_CHAIN_DB.CLEAN.CLEAN_SUPPLY_CHAIN;


-- ROW COUNT

SELECT COUNT(*)
FROM SUPPLY_CHAIN_DB.RAW.RAW_DATACO_SUPPLY_CHAIN;        -- BOTH GOT 180519 ROWS
SELECT COUNT(*)
FROM SUPPLY_CHAIN_DB.CLEAN.CLEAN_SUPPLY_CHAIN;


-- NULL VALUES CHECK

SELECT
    COUNT(*) AS total_rows,
    COUNT(*) - COUNT(DAYS_FOR_SHIPPING_REAL) AS null_days_for_shipping_real,
    COUNT(*) - COUNT(DAYS_FOR_SHIPMENT_SCHEDULED) AS null_days_for_shipment_scheduled,
    COUNT(*) - COUNT(BENEFIT_PER_ORDER) AS null_benefit_per_order,
    COUNT(*) - COUNT(SALES_PER_CUSTOMER) AS null_sales_per_customer,
    COUNT(*) - COUNT(DELIVERY_STATUS) AS null_delivery_status,
    COUNT(*) - COUNT(LATE_DELIVERY_RISK) AS null_late_delivery_risk,
    COUNT(*) - COUNT(CATEGORY_ID) AS null_category_id,
    COUNT(*) - COUNT(CATEGORY_NAME) AS null_category_name,
    COUNT(*) - COUNT(CUSTOMER_CITY) AS null_customer_city,
    COUNT(*) - COUNT(CUSTOMER_COUNTRY) AS null_customer_country,
    COUNT(*) - COUNT(CUSTOMER_SEGMENT) AS null_customer_segment,
    COUNT(*) - COUNT(CUSTOMER_STATE) AS null_customer_state,
    COUNT(*) - COUNT(DEPARTMENT_ID) AS null_department_id,
    COUNT(*) - COUNT(DEPARTMENT_NAME) AS null_department_name,
    COUNT(*) - COUNT(MARKET) AS null_market,
    COUNT(*) - COUNT(ORDER_CITY) AS null_order_city,
    COUNT(*) - COUNT(ORDER_COUNTRY) AS null_order_country,
    COUNT(*) - COUNT(ORDER_CUSTOMER_ID) AS null_order_customer_id,
    COUNT(*) - COUNT(ORDER_DATE) AS null_order_date,
    COUNT(*) - COUNT(ORDER_ID) AS null_order_id,
    COUNT(*) - COUNT(ORDER_ITEM_DISCOUNT) AS null_order_item_discount,
    COUNT(*) - COUNT(ORDER_ITEM_DISCOUNT_RATE) AS null_order_item_discount_rate,
    COUNT(*) - COUNT(ORDER_ITEM_ID) AS null_order_item_id,
    COUNT(*) - COUNT(ORDER_ITEM_PRODUCT_PRICE) AS null_order_item_product_price,
    COUNT(*) - COUNT(ORDER_ITEM_PROFIT_RATIO) AS null_order_item_profit_ratio,
    COUNT(*) - COUNT(ORDER_ITEM_QUANTITY) AS null_order_item_quantity,
    COUNT(*) - COUNT(SALES) AS null_sales,
    COUNT(*) - COUNT(ORDER_ITEM_TOTAL) AS null_order_item_total,
    COUNT(*) - COUNT(ORDER_PROFIT_PER_ORDER) AS null_order_profit_per_order,
    COUNT(*) - COUNT(ORDER_REGION) AS null_order_region,
    COUNT(*) - COUNT(ORDER_STATE) AS null_order_state,
    COUNT(*) - COUNT(ORDER_STATUS) AS null_order_status,
    COUNT(*) - COUNT(PRODUCT_NAME) AS null_product_name,
    COUNT(*) - COUNT(PRODUCT_PRICE) AS null_product_price,
    COUNT(*) - COUNT(PRODUCT_STATUS) AS null_product_status,
    COUNT(*) - COUNT(SHIPPING_DATE) AS null_shipping_date,
    COUNT(*) - COUNT(SHIPPING_MODE) AS null_shipping_mode
FROM SUPPLY_CHAIN_DB.CLEAN.CLEAN_SUPPLY_CHAIN;                  -- NO NULL VALUES FOUND
