USE DATABASE SUPPLY_CHAIN_DB;

USE SCHEMA ANALYTICS;


-- SHIPPING PERFORMANCE

CREATE OR REPLACE VIEW SUPPLY_CHAIN_DB.ANALYTICS.VW_SHIPPING_PERFORMANCE AS
SELECT
shipping_mode,
COUNT(*) AS total_orders,
SUM(late_delivery_risk) AS late_orders,
ROUND(SUM(late_delivery_risk)/COUNT(*)*100,2) AS late_delivery_percentage,
ROUND(AVG(days_for_shipping_real),2) AS avg_shipping_days
FROM SUPPLY_CHAIN_DB.CLEAN.CLEAN_SUPPLY_CHAIN
GROUP BY shipping_mode;

SELECT * FROM SUPPLY_CHAIN_DB.ANALYTICS.VW_SHIPPING_PERFORMANCE;



-- REVENUE BY CATEGORY

CREATE OR REPLACE VIEW SUPPLY_CHAIN_DB.ANALYTICS.VW_REVENUE_BY_CATEGORY AS
SELECT
category_name,
COUNT(DISTINCT order_id) AS total_orders,
ROUND(SUM(sales),2) AS total_revenue,
ROUND(SUM(order_profit_per_order),2) AS total_profit
FROM SUPPLY_CHAIN_DB.CLEAN.CLEAN_SUPPLY_CHAIN
GROUP BY category_name;

select * from SUPPLY_CHAIN_DB.ANALYTICS.VW_REVENUE_BY_CATEGORY;



-- MONTHLY REVENUE

CREATE OR REPLACE VIEW SUPPLY_CHAIN_DB.ANALYTICS.VW_MONTHLY_REVENUE AS
SELECT
DATE_TRUNC('MONTH', order_date) AS order_month,
ROUND(SUM(sales),2) AS monthly_revenue,
ROUND(SUM(order_profit_per_order),2) AS monthly_profit
FROM SUPPLY_CHAIN_DB.CLEAN.CLEAN_SUPPLY_CHAIN
GROUP BY DATE_TRUNC('MONTH', order_date);

select * from SUPPLY_CHAIN_DB.ANALYTICS.VW_MONTHLY_REVENUE;