-- WORKFLOW AUTOMATION TO LOAD CLEAN TABLE FROM RAW TABLE

USE DATABASE SUPPLY_CHAIN_DB;
USE SCHEMA CLEAN;

CREATE OR REPLACE TASK SUPPLY_CHAIN_DB.CLEAN.DAILY_REFRESH_TASK
WAREHOUSE = SUPPLY_CHAIN_WH
SCHEDULE = 'USING CRON 0 0 * * * UTC'
AS
CREATE OR REPLACE TABLE SUPPLY_CHAIN_DB.CLEAN.CLEAN_SUPPLY_CHAIN AS
SELECT
TRY_TO_NUMBER(DAYS_FOR_SHIPPING_REAL) AS DAYS_FOR_SHIPPING_REAL,
TRY_TO_NUMBER(DAYS_FOR_SHIPMENT_SCHEDULED) AS DAYS_FOR_SHIPMENT_SCHEDULED,
TRY_TO_DECIMAL(BENEFIT_PER_ORDER,10,2) AS BENEFIT_PER_ORDER,
TRY_TO_DECIMAL(SALES_PER_CUSTOMER,10,2) AS SALES_PER_CUSTOMER,
DELIVERY_STATUS,
TRY_TO_NUMBER(LATE_DELIVERY_RISK) AS LATE_DELIVERY_RISK,
TRY_TO_NUMBER(CATEGORY_ID) AS CATEGORY_ID,
CATEGORY_NAME,
CUSTOMER_CITY,
CUSTOMER_COUNTRY,
CUSTOMER_SEGMENT,
CUSTOMER_STATE,
MARKET,
ORDER_CITY,
ORDER_COUNTRY,
TRY_TO_TIMESTAMP(ORDER_DATE,'MM/DD/YYYY HH24:MI') AS ORDER_DATE,
TRY_TO_NUMBER(ORDER_ID) AS ORDER_ID,
TRY_TO_DECIMAL(SALES,10,2) AS SALES,
TRY_TO_DECIMAL(ORDER_PROFIT_PER_ORDER,10,2) AS ORDER_PROFIT_PER_ORDER,
PRODUCT_NAME,
TRY_TO_DECIMAL(PRODUCT_PRICE,10,2) AS PRODUCT_PRICE,
TRY_TO_TIMESTAMP(SHIPPING_DATE,'MM/DD/YYYY HH24:MI') AS SHIPPING_DATE,
SHIPPING_MODE
FROM SUPPLY_CHAIN_DB.RAW.RAW_DATACO_SUPPLY_CHAIN;

ALTER TASK DAILY_REFRESH_TASK RESUME;

SHOW TASKS IN SUPPLY_CHAIN_DB.CLEAN;